INSERT INTO categories (title) VALUES ("Most Likely To"),("Story Time"),("Scenarios");
INSERT INTO cards(body,consequence,category) VALUES
("Who is most likely to contract covid?",1,1),
("Who is most likely to get covid and not tell anyone?",1,1),
("Who drank the most during covid?",1,1),
("Who seems to have ordered out the most during quarantine?",1,1),
("Who has gotten the most covid tests?",1,1),
("Who has had the most recent covid test?",1,1),
("Who is hoarding the most toilet paper?",1,1),
("No mask? No service! Which player wears the fanciest one?",1,1),
("Who is most likely to adopt a “quarantine” pet?",1,1),
("Which player has the largest sweatpants collection?",1,1),
("The Covid vaccine is finally available. Who jumps in line first to get it?",1,1),
("Who is most likely to survive a zombie apocalypse?",1,1),
("Who has made the most trips to the fridge today?",1,1),
("Guess which player has worn the same outfit for more than 2 days in a row.",1,1),
("Uh oh! Travel is now banned. Who packs up their car for a road trip?",1,1),
("Who has logged the most hours watching Netflix?",1,1),
("Which player orders takeout when they have food at home?",1,1),
("Hair salons are closed for business. Who takes the scissors into their own hands?",1,1),
("If you had to eat banana bread for the rest of quarantine, which player would you choose to bake it?",1,1),
("Who is most likely to use “Hey all you cool cats and kittens” as their new catch phrase?",1,1),
("Time for a dare! Nominate one player for a TikTok dance challenge.",1,1);